name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: run CI
      uses: devcontainers/ci@v0.3
      with:    
        runCmd: clj -T:build ci
        push: never


